permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "soken"
email: "terrylog_1986@126.com"
description: "开发者"
github_username:  "soken1986"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "soken1986"



url: "http://soken1986.github.io"
imgrepo: "http://soken1986.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
#gems: [jekyll-paginate]

